version: '3.7'
services:
  postgres:
    image: postgres:13-alpine
    ports:
      - '5432:5432'
    volumes:
      - ./data:/var/lib/postgresql/data
    environment:
      - POSTGRES_D8=app
      - POSTGRES_USER=app
      - POSTGRES_PASSWORD=G17abt5TpY9123Wer